extends KinematicBody

onready var nav = get_parent()

var path = [] # waypoints generated by nav
var path_node = 0 # index into path

var speed = 400

onready var player = $"../Player"
onready var timer = $Timer

# Called when the node enters the scene tree for the first time.
func _ready():
	var err = timer.connect("timeout", self, "_on_Timer_timeout")
	if err:
		print(err)


func _physics_process(delta):
			
	var direction : Vector3
	if path_node < path.size():
		direction = (path[path_node] - global_transform.origin)
		if direction.length() < 1:
			path_node += 1
	#move_and_slide(direction.normalized() * speed*delta + 0.98*Vector3.DOWN*delta) # gravity
	var kinematic = move_and_slide(direction.normalized() * speed*delta) # no gravity
	if kinematic:
		yield(get_tree().create_timer(1.0), "timeout")
	#	kinematic = move_and_collide(-0.1*kinematic.remainder + 0.1*Vector3.UP)
	

func move_to(target_pos):
	path = nav.get_simple_path(global_transform.origin, target_pos)	
	path_node = 0
	#print(path)

func _on_Timer_timeout():
	move_to(player.global_transform.origin)
